/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ERP_JoseMesaPadilla.view;

import java.awt.Color;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author josem
 */
public class principaljmp extends javax.swing.JFrame {

    /**
     * Creates new form principaljmp
     */
    public principaljmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraHerramientas = new javax.swing.JPanel();
        etiCerrar = new javax.swing.JLabel();
        jPanelBarraPresupuestos = new javax.swing.JPanel();
        iconoPresupuestos = new javax.swing.JLabel();
        jPanelBarraFacturas = new javax.swing.JPanel();
        iconoFacturas = new javax.swing.JLabel();
        jPanelBarraClientes = new javax.swing.JPanel();
        iconoClientes = new javax.swing.JLabel();
        jPanelBarraProyectos = new javax.swing.JPanel();
        iconoProyectos = new javax.swing.JLabel();
        jPanelBarraInformes = new javax.swing.JPanel();
        iconoInformes = new javax.swing.JLabel();
        jPanelBarraConfig = new javax.swing.JPanel();
        iconoConfiguracion = new javax.swing.JLabel();
        iconoMinimizar = new javax.swing.JLabel();
        jPanelMenuLateral = new javax.swing.JPanel();
        jPanelPresupuestos = new javax.swing.JPanel();
        etiPresupuestos = new javax.swing.JLabel();
        etiIconoPresupuestos = new javax.swing.JLabel();
        jPanelFacturas = new javax.swing.JPanel();
        etiFacturas = new javax.swing.JLabel();
        etiIconoFacturas = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        etiClientes = new javax.swing.JLabel();
        etiIconoClientes = new javax.swing.JLabel();
        jPanelProyectos = new javax.swing.JPanel();
        etiProyectos = new javax.swing.JLabel();
        etiIconoProyectos = new javax.swing.JLabel();
        jPanelInformes = new javax.swing.JPanel();
        etiIconoInformes = new javax.swing.JLabel();
        etiInformes = new javax.swing.JLabel();
        jPanelConfig = new javax.swing.JPanel();
        etiConfig = new javax.swing.JLabel();
        etiIconoConfig = new javax.swing.JLabel();
        jPanelUsuario = new javax.swing.JPanel();
        etiLogoUsuario = new javax.swing.JLabel();
        etiNombreUsuario = new javax.swing.JLabel();
        etiBarraSuperior = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JTabbedPane();
        panelPresupuestos = new javax.swing.JPanel();
        etiPanelPresupuestos = new javax.swing.JLabel();
        panelFacturas = new javax.swing.JPanel();
        etiPanelFacturas = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        etiPanelClientes = new javax.swing.JLabel();
        panelInformes = new javax.swing.JPanel();
        etiPanelInformes = new javax.swing.JLabel();
        panelConfig = new javax.swing.JPanel();
        etiPanelConfig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TFG José Mesa Padilla");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraHerramientas.setBackground(new java.awt.Color(0, 0, 0));
        barraHerramientas.setOpaque(false);
        barraHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        etiCerrar.setForeground(new java.awt.Color(255, 255, 255));
        etiCerrar.setText("X");
        etiCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCerrarMouseClicked(evt);
            }
        });
        barraHerramientas.add(etiCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 130));

        jPanelBarraPresupuestos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraPresupuestos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraPresupuestosMouseMoved(evt);
            }
        });
        jPanelBarraPresupuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraPresupuestosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraPresupuestosMouseExited(evt);
            }
        });
        jPanelBarraPresupuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoPresupuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/presupuestosBarra.png"))); // NOI18N
        jPanelBarraPresupuestos.add(iconoPresupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 130));

        barraHerramientas.add(jPanelBarraPresupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 100, 130));

        jPanelBarraFacturas.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraFacturas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraFacturasMouseMoved(evt);
            }
        });
        jPanelBarraFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraFacturasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraFacturasMouseExited(evt);
            }
        });
        jPanelBarraFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/facturaBarra.png"))); // NOI18N
        jPanelBarraFacturas.add(iconoFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 130));

        barraHerramientas.add(jPanelBarraFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, 130));

        jPanelBarraClientes.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraClientesMouseMoved(evt);
            }
        });
        jPanelBarraClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraClientesMouseExited(evt);
            }
        });
        jPanelBarraClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/clientesBarra.png"))); // NOI18N
        jPanelBarraClientes.add(iconoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 130));

        barraHerramientas.add(jPanelBarraClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 100, 130));

        jPanelBarraProyectos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraProyectos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraProyectosMouseMoved(evt);
            }
        });
        jPanelBarraProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraProyectosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraProyectosMouseExited(evt);
            }
        });
        jPanelBarraProyectos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/proyectosBarra.png"))); // NOI18N
        jPanelBarraProyectos.add(iconoProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 130));

        barraHerramientas.add(jPanelBarraProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 130));

        jPanelBarraInformes.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraInformes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraInformesMouseMoved(evt);
            }
        });
        jPanelBarraInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraInformesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraInformesMouseExited(evt);
            }
        });
        jPanelBarraInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/estadisticasBarra.png"))); // NOI18N
        jPanelBarraInformes.add(iconoInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 130));

        barraHerramientas.add(jPanelBarraInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 100, 130));

        jPanelBarraConfig.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBarraConfig.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelBarraConfigMouseMoved(evt);
            }
        });
        jPanelBarraConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarraConfigMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBarraConfigMouseExited(evt);
            }
        });
        jPanelBarraConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/configuracionBarra.png"))); // NOI18N
        jPanelBarraConfig.add(iconoConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 130));

        barraHerramientas.add(jPanelBarraConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 100, 130));

        iconoMinimizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        iconoMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        iconoMinimizar.setText("-");
        iconoMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoMinimizarMouseClicked(evt);
            }
        });
        barraHerramientas.add(iconoMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 40, 130));

        getContentPane().add(barraHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1060, 130));

        jPanelMenuLateral.setBackground(new java.awt.Color(100, 101, 102));
        jPanelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPresupuestos.setBackground(new java.awt.Color(100, 101, 102));
        jPanelPresupuestos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelPresupuestosMouseMoved(evt);
            }
        });
        jPanelPresupuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPresupuestosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPresupuestosMouseExited(evt);
            }
        });
        jPanelPresupuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiPresupuestos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiPresupuestos.setForeground(new java.awt.Color(255, 255, 255));
        etiPresupuestos.setText("PRESUPUESTOS");
        jPanelPresupuestos.add(etiPresupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        etiIconoPresupuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/presupuestos.png"))); // NOI18N
        jPanelPresupuestos.add(etiIconoPresupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        jPanelMenuLateral.add(jPanelPresupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 350, 60));

        jPanelFacturas.setBackground(new java.awt.Color(100, 101, 102));
        jPanelFacturas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelFacturasMouseMoved(evt);
            }
        });
        jPanelFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFacturasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFacturasMouseExited(evt);
            }
        });
        jPanelFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiFacturas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiFacturas.setForeground(new java.awt.Color(255, 255, 255));
        etiFacturas.setText("FACTURAS");
        jPanelFacturas.add(etiFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        etiIconoFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/factura.png"))); // NOI18N
        jPanelFacturas.add(etiIconoFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        jPanelMenuLateral.add(jPanelFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 350, 60));

        jPanelClientes.setBackground(new java.awt.Color(100, 101, 102));
        jPanelClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseMoved(evt);
            }
        });
        jPanelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseExited(evt);
            }
        });
        jPanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiClientes.setForeground(new java.awt.Color(255, 255, 255));
        etiClientes.setText("CLIENTES");
        jPanelClientes.add(etiClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        etiIconoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/clientes.png"))); // NOI18N
        jPanelClientes.add(etiIconoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        jPanelMenuLateral.add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 350, 60));

        jPanelProyectos.setBackground(new java.awt.Color(100, 101, 102));
        jPanelProyectos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelProyectosMouseMoved(evt);
            }
        });
        jPanelProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProyectosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelProyectosMouseExited(evt);
            }
        });
        jPanelProyectos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiProyectos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiProyectos.setForeground(new java.awt.Color(255, 255, 255));
        etiProyectos.setText("PROYECTOS");
        jPanelProyectos.add(etiProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        etiIconoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/proyectos.png"))); // NOI18N
        jPanelProyectos.add(etiIconoProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 60));

        jPanelMenuLateral.add(jPanelProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 350, 60));

        jPanelInformes.setBackground(new java.awt.Color(100, 101, 102));
        jPanelInformes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelInformesMouseMoved(evt);
            }
        });
        jPanelInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInformesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelInformesMouseExited(evt);
            }
        });
        jPanelInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiIconoInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/estadisticas.png"))); // NOI18N
        jPanelInformes.add(etiIconoInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        etiInformes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiInformes.setForeground(new java.awt.Color(255, 255, 255));
        etiInformes.setText("INFORMES");
        jPanelInformes.add(etiInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        jPanelMenuLateral.add(jPanelInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 350, 60));

        jPanelConfig.setBackground(new java.awt.Color(100, 101, 102));
        jPanelConfig.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelConfigMouseMoved(evt);
            }
        });
        jPanelConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConfigMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelConfigMouseExited(evt);
            }
        });
        jPanelConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiConfig.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        etiConfig.setForeground(new java.awt.Color(255, 255, 255));
        etiConfig.setText("CONFIGURACIÓN");
        jPanelConfig.add(etiConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 60));

        etiIconoConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/configuracion.png"))); // NOI18N
        jPanelConfig.add(etiIconoConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        jPanelMenuLateral.add(jPanelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 350, 60));

        jPanelUsuario.setBackground(new java.awt.Color(178, 179, 179));
        jPanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiLogoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiLogoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/fotoUsuario.png"))); // NOI18N
        jPanelUsuario.add(etiLogoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, -1));

        etiNombreUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        etiNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        etiNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiNombreUsuario.setText("José Mesa Padilla");
        etiNombreUsuario.setToolTipText("");
        jPanelUsuario.add(etiNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 210, 350, 110));

        jPanelMenuLateral.add(jPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        getContentPane().add(jPanelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 830));

        etiBarraSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERP_JoseMesaPadilla/imagenes/barraSuperior.png"))); // NOI18N
        getContentPane().add(etiBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1060, 130));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panelPresupuestos.setBackground(new java.awt.Color(255, 255, 255));

        etiPanelPresupuestos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiPanelPresupuestos.setForeground(new java.awt.Color(101, 101, 102));
        etiPanelPresupuestos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPanelPresupuestos.setText("PRESUPUESTOS");

        javax.swing.GroupLayout panelPresupuestosLayout = new javax.swing.GroupLayout(panelPresupuestos);
        panelPresupuestos.setLayout(panelPresupuestosLayout);
        panelPresupuestosLayout.setHorizontalGroup(
            panelPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelPresupuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        panelPresupuestosLayout.setVerticalGroup(
            panelPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelPresupuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("tab2", panelPresupuestos);

        panelFacturas.setBackground(new java.awt.Color(255, 255, 255));

        etiPanelFacturas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiPanelFacturas.setForeground(new java.awt.Color(101, 101, 102));
        etiPanelFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPanelFacturas.setText("FACTURAS");

        javax.swing.GroupLayout panelFacturasLayout = new javax.swing.GroupLayout(panelFacturas);
        panelFacturas.setLayout(panelFacturasLayout);
        panelFacturasLayout.setHorizontalGroup(
            panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        panelFacturasLayout.setVerticalGroup(
            panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("tab3", panelFacturas);

        panelClientes.setBackground(new java.awt.Color(255, 255, 255));

        etiPanelClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiPanelClientes.setForeground(new java.awt.Color(101, 101, 102));
        etiPanelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPanelClientes.setText("CLIENTES");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("tab4", panelClientes);

        panelInformes.setBackground(new java.awt.Color(255, 255, 255));

        etiPanelInformes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiPanelInformes.setForeground(new java.awt.Color(101, 101, 102));
        etiPanelInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPanelInformes.setText("INFORMES");

        javax.swing.GroupLayout panelInformesLayout = new javax.swing.GroupLayout(panelInformes);
        panelInformes.setLayout(panelInformesLayout);
        panelInformesLayout.setHorizontalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelInformes, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        panelInformesLayout.setVerticalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelInformes, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("tab5", panelInformes);

        panelConfig.setBackground(new java.awt.Color(255, 255, 255));

        etiPanelConfig.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        etiPanelConfig.setForeground(new java.awt.Color(101, 101, 102));
        etiPanelConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiPanelConfig.setText("CONFIGURACIÓN");

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("tab6", panelConfig);

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 1060, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProyectosMouseClicked
        panelPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_jPanelProyectosMouseClicked

    private void jPanelPresupuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPresupuestosMouseClicked
        panelPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelPresupuestosMouseClicked

    private void jPanelFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFacturasMouseClicked
        panelPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelFacturasMouseClicked

    private void jPanelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseClicked
        panelPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_jPanelClientesMouseClicked

    private void jPanelInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInformesMouseClicked
        panelPrincipal.setSelectedIndex(4);
    }//GEN-LAST:event_jPanelInformesMouseClicked

    private void jPanelConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfigMouseClicked
        panelPrincipal.setSelectedIndex(5);
    }//GEN-LAST:event_jPanelConfigMouseClicked

    private void jPanelProyectosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProyectosMouseMoved
        jPanelProyectos.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelProyectosMouseMoved

    private void jPanelProyectosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProyectosMouseExited
        jPanelProyectos.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelProyectosMouseExited

    private void jPanelPresupuestosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPresupuestosMouseMoved
        jPanelPresupuestos.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelPresupuestosMouseMoved

    private void jPanelPresupuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPresupuestosMouseExited
        jPanelPresupuestos.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelPresupuestosMouseExited

    private void jPanelFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFacturasMouseExited
        jPanelFacturas.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelFacturasMouseExited

    private void jPanelFacturasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFacturasMouseMoved
        jPanelFacturas.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelFacturasMouseMoved

    private void jPanelClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseMoved
        jPanelClientes.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelClientesMouseMoved

    private void jPanelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseExited
        jPanelClientes.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelClientesMouseExited

    private void jPanelInformesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInformesMouseMoved
        jPanelInformes.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelInformesMouseMoved

    private void jPanelInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInformesMouseExited
        jPanelInformes.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelInformesMouseExited

    private void jPanelConfigMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfigMouseMoved
        jPanelConfig.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelConfigMouseMoved

    private void jPanelConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfigMouseExited
        jPanelConfig.setBackground(new Color(100, 101, 102));
    }//GEN-LAST:event_jPanelConfigMouseExited

    private void etiCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_etiCerrarMouseClicked

    private void iconoMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMinimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_iconoMinimizarMouseClicked

    private void jPanelBarraPresupuestosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraPresupuestosMouseMoved
        jPanelBarraPresupuestos.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraPresupuestosMouseMoved

    private void jPanelBarraPresupuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraPresupuestosMouseClicked
        panelPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelBarraPresupuestosMouseClicked

    private void jPanelBarraPresupuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraPresupuestosMouseExited
        jPanelBarraPresupuestos.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraPresupuestosMouseExited

    private void jPanelBarraFacturasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraFacturasMouseMoved
        jPanelBarraFacturas.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraFacturasMouseMoved

    private void jPanelBarraFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraFacturasMouseClicked
        panelPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelBarraFacturasMouseClicked

    private void jPanelBarraFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraFacturasMouseExited
        jPanelBarraFacturas.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraFacturasMouseExited

    private void jPanelBarraProyectosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraProyectosMouseMoved
        jPanelBarraProyectos.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraProyectosMouseMoved

    private void jPanelBarraProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraProyectosMouseClicked
        panelPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_jPanelBarraProyectosMouseClicked

    private void jPanelBarraProyectosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraProyectosMouseExited
        jPanelBarraProyectos.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraProyectosMouseExited

    private void jPanelBarraConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraConfigMouseExited
        jPanelBarraConfig.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraConfigMouseExited

    private void jPanelBarraConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraConfigMouseClicked
        panelPrincipal.setSelectedIndex(5);
    }//GEN-LAST:event_jPanelBarraConfigMouseClicked

    private void jPanelBarraConfigMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraConfigMouseMoved
        jPanelBarraConfig.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraConfigMouseMoved

    private void jPanelBarraInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraInformesMouseExited
        jPanelBarraInformes.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraInformesMouseExited

    private void jPanelBarraInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraInformesMouseClicked
        panelPrincipal.setSelectedIndex(4);
    }//GEN-LAST:event_jPanelBarraInformesMouseClicked

    private void jPanelBarraInformesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraInformesMouseMoved
        jPanelBarraInformes.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraInformesMouseMoved

    private void jPanelBarraClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraClientesMouseExited
        jPanelBarraClientes.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jPanelBarraClientesMouseExited

    private void jPanelBarraClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraClientesMouseClicked
        panelPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_jPanelBarraClientesMouseClicked

    private void jPanelBarraClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarraClientesMouseMoved
        jPanelBarraClientes.setBackground(new Color(255, 182, 0));
    }//GEN-LAST:event_jPanelBarraClientesMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principaljmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principaljmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principaljmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principaljmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principaljmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraHerramientas;
    private javax.swing.JLabel etiBarraSuperior;
    private javax.swing.JLabel etiCerrar;
    private javax.swing.JLabel etiClientes;
    private javax.swing.JLabel etiConfig;
    private javax.swing.JLabel etiFacturas;
    private javax.swing.JLabel etiIconoClientes;
    private javax.swing.JLabel etiIconoConfig;
    private javax.swing.JLabel etiIconoFacturas;
    private javax.swing.JLabel etiIconoInformes;
    private javax.swing.JLabel etiIconoPresupuestos;
    private javax.swing.JLabel etiIconoProyectos;
    private javax.swing.JLabel etiInformes;
    private javax.swing.JLabel etiLogoUsuario;
    private javax.swing.JLabel etiNombreUsuario;
    private javax.swing.JLabel etiPanelClientes;
    private javax.swing.JLabel etiPanelConfig;
    private javax.swing.JLabel etiPanelFacturas;
    private javax.swing.JLabel etiPanelInformes;
    private javax.swing.JLabel etiPanelPresupuestos;
    private javax.swing.JLabel etiPresupuestos;
    private javax.swing.JLabel etiProyectos;
    private javax.swing.JLabel iconoClientes;
    private javax.swing.JLabel iconoConfiguracion;
    private javax.swing.JLabel iconoFacturas;
    private javax.swing.JLabel iconoInformes;
    private javax.swing.JLabel iconoMinimizar;
    private javax.swing.JLabel iconoPresupuestos;
    private javax.swing.JLabel iconoProyectos;
    private javax.swing.JPanel jPanelBarraClientes;
    private javax.swing.JPanel jPanelBarraConfig;
    private javax.swing.JPanel jPanelBarraFacturas;
    private javax.swing.JPanel jPanelBarraInformes;
    private javax.swing.JPanel jPanelBarraPresupuestos;
    private javax.swing.JPanel jPanelBarraProyectos;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JPanel jPanelFacturas;
    private javax.swing.JPanel jPanelInformes;
    private javax.swing.JPanel jPanelMenuLateral;
    private javax.swing.JPanel jPanelPresupuestos;
    private javax.swing.JPanel jPanelProyectos;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelFacturas;
    private javax.swing.JPanel panelInformes;
    private javax.swing.JPanel panelPresupuestos;
    private javax.swing.JTabbedPane panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
